package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

/**
 * CarreraMateriaId generated by hbm2java
 */
public class CarreraMateriaId implements java.io.Serializable {

	private int idCarrera;
	private int idMateria;

	public CarreraMateriaId() {
	}

	public CarreraMateriaId(int idCarrera, int idMateria) {
		this.idCarrera = idCarrera;
		this.idMateria = idMateria;
	}

	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarreraMateriaId))
			return false;
		CarreraMateriaId castOther = (CarreraMateriaId) other;

		return (this.getIdCarrera() == castOther.getIdCarrera())
				&& (this.getIdMateria() == castOther.getIdMateria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCarrera();
		result = 37 * result + this.getIdMateria();
		return result;
	}

}
