package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

/**
 * CarreraEstudiante generated by hbm2java
 */
public class CarreraEstudiante implements java.io.Serializable {

	private CarreraEstudianteId id;
	private Carrera carrera;
	private Persona persona;

	public CarreraEstudiante() {
	}

	public CarreraEstudiante(CarreraEstudianteId id, Carrera carrera,
			Persona persona) {
		this.id = id;
		this.carrera = carrera;
		this.persona = persona;
	}

	public CarreraEstudianteId getId() {
		return this.id;
	}

	public void setId(CarreraEstudianteId id) {
		this.id = id;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
