package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera implements java.io.Serializable {

	private int idCarrera;
	private Facultad facultad;
	private String nombreCarrera;
	private Integer totalCreditos;
	private Character estadoCarrera;
	private Set<CarreraMateria> carreraMaterias = new HashSet<CarreraMateria>(0);
	private Set<CarreraEstudiante> carreraEstudiantes = new HashSet<CarreraEstudiante>(
			0);

	public Carrera() {
	}

	public Carrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	public Carrera(int idCarrera, Facultad facultad, String nombreCarrera,
			Integer totalCreditos, Character estadoCarrera,
			Set<CarreraMateria> carreraMaterias,
			Set<CarreraEstudiante> carreraEstudiantes) {
		this.idCarrera = idCarrera;
		this.facultad = facultad;
		this.nombreCarrera = nombreCarrera;
		this.totalCreditos = totalCreditos;
		this.estadoCarrera = estadoCarrera;
		this.carreraMaterias = carreraMaterias;
		this.carreraEstudiantes = carreraEstudiantes;
	}

	public int getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(int idCarrera) {
		this.idCarrera = idCarrera;
	}

	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	public Integer getTotalCreditos() {
		return this.totalCreditos;
	}

	public void setTotalCreditos(Integer totalCreditos) {
		this.totalCreditos = totalCreditos;
	}

	public Character getEstadoCarrera() {
		return this.estadoCarrera;
	}

	public void setEstadoCarrera(Character estadoCarrera) {
		this.estadoCarrera = estadoCarrera;
	}

	public Set<CarreraMateria> getCarreraMaterias() {
		return this.carreraMaterias;
	}

	public void setCarreraMaterias(Set<CarreraMateria> carreraMaterias) {
		this.carreraMaterias = carreraMaterias;
	}

	public Set<CarreraEstudiante> getCarreraEstudiantes() {
		return this.carreraEstudiantes;
	}

	public void setCarreraEstudiantes(Set<CarreraEstudiante> carreraEstudiantes) {
		this.carreraEstudiantes = carreraEstudiantes;
	}

}
