package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

/**
 * CarreraMateria generated by hbm2java
 */
public class CarreraMateria implements java.io.Serializable {

	private CarreraMateriaId id;
	private Carrera carrera;
	private Materia materia;

	public CarreraMateria() {
	}

	public CarreraMateria(CarreraMateriaId id, Carrera carrera, Materia materia) {
		this.id = id;
		this.carrera = carrera;
		this.materia = materia;
	}

	public CarreraMateriaId getId() {
		return this.id;
	}

	public void setId(CarreraMateriaId id) {
		this.id = id;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

}
