package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Facultad generated by hbm2java
 */
public class Facultad implements java.io.Serializable {

	private int idFacultad;
	private String nombreFacultad;
	private Character estadoFacultad;
	private Set<Carrera> carreras = new HashSet<Carrera>(0);

	public Facultad() {
	}

	public Facultad(int idFacultad) {
		this.idFacultad = idFacultad;
	}

	public Facultad(int idFacultad, String nombreFacultad,
			Character estadoFacultad, Set<Carrera> carreras) {
		this.idFacultad = idFacultad;
		this.nombreFacultad = nombreFacultad;
		this.estadoFacultad = estadoFacultad;
		this.carreras = carreras;
	}

	public int getIdFacultad() {
		return this.idFacultad;
	}

	public void setIdFacultad(int idFacultad) {
		this.idFacultad = idFacultad;
	}

	public String getNombreFacultad() {
		return this.nombreFacultad;
	}

	public void setNombreFacultad(String nombreFacultad) {
		this.nombreFacultad = nombreFacultad;
	}

	public Character getEstadoFacultad() {
		return this.estadoFacultad;
	}

	public void setEstadoFacultad(Character estadoFacultad) {
		this.estadoFacultad = estadoFacultad;
	}

	public Set<Carrera> getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set<Carrera> carreras) {
		this.carreras = carreras;
	}

}
