package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia implements java.io.Serializable {

	private int idMateria;
	private String nombreMateria;
	private Integer creditos;
	private Character estadoMateria;
	private Set<MateriaMatricula> materiaMatriculas = new HashSet<MateriaMatricula>(
			0);
	private Set<CarreraMateria> carreraMaterias = new HashSet<CarreraMateria>(0);

	public Materia() {
	}

	public Materia(int idMateria) {
		this.idMateria = idMateria;
	}

	public Materia(int idMateria, String nombreMateria, Integer creditos,
			Character estadoMateria, Set<MateriaMatricula> materiaMatriculas,
			Set<CarreraMateria> carreraMaterias) {
		this.idMateria = idMateria;
		this.nombreMateria = nombreMateria;
		this.creditos = creditos;
		this.estadoMateria = estadoMateria;
		this.materiaMatriculas = materiaMatriculas;
		this.carreraMaterias = carreraMaterias;
	}

	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}

	public Integer getCreditos() {
		return this.creditos;
	}

	public void setCreditos(Integer creditos) {
		this.creditos = creditos;
	}

	public Character getEstadoMateria() {
		return this.estadoMateria;
	}

	public void setEstadoMateria(Character estadoMateria) {
		this.estadoMateria = estadoMateria;
	}

	public Set<MateriaMatricula> getMateriaMatriculas() {
		return this.materiaMatriculas;
	}

	public void setMateriaMatriculas(Set<MateriaMatricula> materiaMatriculas) {
		this.materiaMatriculas = materiaMatriculas;
	}

	public Set<CarreraMateria> getCarreraMaterias() {
		return this.carreraMaterias;
	}

	public void setCarreraMaterias(Set<CarreraMateria> carreraMaterias) {
		this.carreraMaterias = carreraMaterias;
	}

}
