package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

/**
 * MateriaMatriculaId generated by hbm2java
 */
public class MateriaMatriculaId implements java.io.Serializable {

	private int idMateria;
	private int idMatricula;

	public MateriaMatriculaId() {
	}

	public MateriaMatriculaId(int idMateria, int idMatricula) {
		this.idMateria = idMateria;
		this.idMatricula = idMatricula;
	}

	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	public int getIdMatricula() {
		return this.idMatricula;
	}

	public void setIdMatricula(int idMatricula) {
		this.idMatricula = idMatricula;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MateriaMatriculaId))
			return false;
		MateriaMatriculaId castOther = (MateriaMatriculaId) other;

		return (this.getIdMateria() == castOther.getIdMateria())
				&& (this.getIdMatricula() == castOther.getIdMatricula());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMateria();
		result = 37 * result + this.getIdMatricula();
		return result;
	}

}
