package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula implements java.io.Serializable {

	private int idMatricula;
	private Persona persona;
	private Integer totalCreditos;
	private Integer totalMatricula;
	private Character estadoMatricula;
	private Set<MateriaMatricula> materiaMatriculas = new HashSet<MateriaMatricula>(
			0);

	public Matricula() {
	}

	public Matricula(int idMatricula) {
		this.idMatricula = idMatricula;
	}

	public Matricula(int idMatricula, Persona persona, Integer totalCreditos,
			Integer totalMatricula, Character estadoMatricula,
			Set<MateriaMatricula> materiaMatriculas) {
		this.idMatricula = idMatricula;
		this.persona = persona;
		this.totalCreditos = totalCreditos;
		this.totalMatricula = totalMatricula;
		this.estadoMatricula = estadoMatricula;
		this.materiaMatriculas = materiaMatriculas;
	}

	public int getIdMatricula() {
		return this.idMatricula;
	}

	public void setIdMatricula(int idMatricula) {
		this.idMatricula = idMatricula;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Integer getTotalCreditos() {
		return this.totalCreditos;
	}

	public void setTotalCreditos(Integer totalCreditos) {
		this.totalCreditos = totalCreditos;
	}

	public Integer getTotalMatricula() {
		return this.totalMatricula;
	}

	public void setTotalMatricula(Integer totalMatricula) {
		this.totalMatricula = totalMatricula;
	}

	public Character getEstadoMatricula() {
		return this.estadoMatricula;
	}

	public void setEstadoMatricula(Character estadoMatricula) {
		this.estadoMatricula = estadoMatricula;
	}

	public Set<MateriaMatricula> getMateriaMatriculas() {
		return this.materiaMatriculas;
	}

	public void setMateriaMatriculas(Set<MateriaMatricula> materiaMatriculas) {
		this.materiaMatriculas = materiaMatriculas;
	}

}
