package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	private int idPerfil;
	private String nombrePerfil;
	private Character estadoPerfil;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Perfil() {
	}

	public Perfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public Perfil(int idPerfil, String nombrePerfil, Character estadoPerfil,
			Set<Persona> personas) {
		this.idPerfil = idPerfil;
		this.nombrePerfil = nombrePerfil;
		this.estadoPerfil = estadoPerfil;
		this.personas = personas;
	}

	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public String getNombrePerfil() {
		return this.nombrePerfil;
	}

	public void setNombrePerfil(String nombrePerfil) {
		this.nombrePerfil = nombrePerfil;
	}

	public Character getEstadoPerfil() {
		return this.estadoPerfil;
	}

	public void setEstadoPerfil(Character estadoPerfil) {
		this.estadoPerfil = estadoPerfil;
	}

	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
