package Entidades;

// Generated 12-oct-2015 22:22:37 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private int idPersona;
	private Perfil perfil;
	private String nombrePersona;
	private String apellidosPersona;
	private Date fechaNacimiento;
	private String lugarNacimiento;
	private String direccion;
	private String correoElectronico;
	private Character estadoPersona;
	private String contrasena;
	private Set<CarreraEstudiante> carreraEstudiantes = new HashSet<CarreraEstudiante>(
			0);
	private Set<Matricula> matriculas = new HashSet<Matricula>(0);
	private Set<Telefonos> telefonoses = new HashSet<Telefonos>(0);

	public Persona() {
	}

	public Persona(int idPersona) {
		this.idPersona = idPersona;
	}

	public Persona(int idPersona, Perfil perfil, String nombrePersona,
			String apellidosPersona, Date fechaNacimiento,
			String lugarNacimiento, String direccion, String correoElectronico,
			Character estadoPersona, String contrasena,
			Set<CarreraEstudiante> carreraEstudiantes,
			Set<Matricula> matriculas, Set<Telefonos> telefonoses) {
		this.idPersona = idPersona;
		this.perfil = perfil;
		this.nombrePersona = nombrePersona;
		this.apellidosPersona = apellidosPersona;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarNacimiento = lugarNacimiento;
		this.direccion = direccion;
		this.correoElectronico = correoElectronico;
		this.estadoPersona = estadoPersona;
		this.contrasena = contrasena;
		this.carreraEstudiantes = carreraEstudiantes;
		this.matriculas = matriculas;
		this.telefonoses = telefonoses;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getNombrePersona() {
		return this.nombrePersona;
	}

	public void setNombrePersona(String nombrePersona) {
		this.nombrePersona = nombrePersona;
	}

	public String getApellidosPersona() {
		return this.apellidosPersona;
	}

	public void setApellidosPersona(String apellidosPersona) {
		this.apellidosPersona = apellidosPersona;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public Character getEstadoPersona() {
		return this.estadoPersona;
	}

	public void setEstadoPersona(Character estadoPersona) {
		this.estadoPersona = estadoPersona;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public Set<CarreraEstudiante> getCarreraEstudiantes() {
		return this.carreraEstudiantes;
	}

	public void setCarreraEstudiantes(Set<CarreraEstudiante> carreraEstudiantes) {
		this.carreraEstudiantes = carreraEstudiantes;
	}

	public Set<Matricula> getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set<Matricula> matriculas) {
		this.matriculas = matriculas;
	}

	public Set<Telefonos> getTelefonoses() {
		return this.telefonoses;
	}

	public void setTelefonoses(Set<Telefonos> telefonoses) {
		this.telefonoses = telefonoses;
	}

}
