package co.ueb.matriculas.model;

// Generated 02-nov-2015 12:47:33 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 746290141466856029L;
	private BigDecimal idCarrera;
	private Facultad facultad;
	private String nombreCarrera;
	private BigDecimal totalCreditos;
	private Character estadoCarrera;
	private Set<Materia> materias = new HashSet<Materia>(0);
	private Set<Persona> carreraEstudiantes = new HashSet<Persona>(0);

	public Carrera() {
	}

	public Carrera(BigDecimal idCarrera) {
		this.idCarrera = idCarrera;
	}

	public Carrera(BigDecimal idCarrera, Facultad facultad,
			String nombreCarrera, BigDecimal totalCreditos,
			Character estadoCarrera, Set<Materia> materias, Set<Persona> carreraEstudiantes) {
		this.idCarrera = idCarrera;
		this.facultad = facultad;
		this.nombreCarrera = nombreCarrera;
		this.totalCreditos = totalCreditos;
		this.estadoCarrera = estadoCarrera;
		this.materias = materias;
		this.carreraEstudiantes = carreraEstudiantes;
	}

	public BigDecimal getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(BigDecimal idCarrera) {
		this.idCarrera = idCarrera;
	}

	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	public String getNombreCarrera() {
		return this.nombreCarrera;
	}

	public void setNombreCarrera(String nombreCarrera) {
		this.nombreCarrera = nombreCarrera;
	}

	public BigDecimal getTotalCreditos() {
		return this.totalCreditos;
	}

	public void setTotalCreditos(BigDecimal totalCreditos) {
		this.totalCreditos = totalCreditos;
	}

	public Character getEstadoCarrera() {
		return this.estadoCarrera;
	}

	public void setEstadoCarrera(Character estadoCarrera) {
		this.estadoCarrera = estadoCarrera;
	}

	public Set<Materia> getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set<Materia> materias) {
		this.materias = materias;
	}

	public Set<Persona> getCarreraEstudiantes() {
		return this.carreraEstudiantes;
	}

	public void setCarreraEstudiantes(Set<Persona> carreraEstudiantes) {
		this.carreraEstudiantes = carreraEstudiantes;
	}

	

	@Override
	public String toString() {
		return "Carrera [idCarrera=" + idCarrera + ", facultad=" + facultad
				+ ", nombreCarrera=" + nombreCarrera + ", totalCreditos="
				+ totalCreditos + ", estadoCarrera=" + estadoCarrera
				+ "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((idCarrera == null) ? 0 : idCarrera.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Carrera other = (Carrera) obj;
		if (idCarrera == null) {
			if (other.idCarrera != null)
				return false;
		} else if (!idCarrera.equals(other.idCarrera))
			return false;
		return true;
	}

	
		
}
