package co.ueb.matriculas.model;

// Generated 02-nov-2015 12:47:33 by Hibernate Tools 4.3.1

/**
 * CarreraEstudiante generated by hbm2java
 */
public class CarreraEstudiante implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7705503768644167309L;
	private CarreraEstudianteId id;
	private Persona persona;
	private Carrera carrera;

	public CarreraEstudiante() {
	}

	public CarreraEstudiante(CarreraEstudianteId id, Persona persona,
			Carrera carrera) {
		this.id = id;
		this.persona = persona;
		this.carrera = carrera;
	}

	public CarreraEstudianteId getId() {
		return this.id;
	}

	public void setId(CarreraEstudianteId id) {
		this.id = id;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carrera == null) ? 0 : carrera.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((persona == null) ? 0 : persona.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CarreraEstudiante other = (CarreraEstudiante) obj;
		if (carrera == null) {
			if (other.carrera != null)
				return false;
		} else if (!carrera.equals(other.carrera))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (persona == null) {
			if (other.persona != null)
				return false;
		} else if (!persona.equals(other.persona))
			return false;
		return true;
	}
	
	

}
