package co.ueb.matriculas.model;

// Generated Nov 1, 2015 5:44:57 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * CarreraEstudianteId generated by hbm2java
 */
public class CarreraEstudianteId implements java.io.Serializable {

	private BigDecimal idPersona;
	private BigDecimal idCarrera;

	public CarreraEstudianteId() {
	}

	public CarreraEstudianteId(BigDecimal idPersona, BigDecimal idCarrera) {
		this.idPersona = idPersona;
		this.idCarrera = idCarrera;
	}

	public BigDecimal getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(BigDecimal idPersona) {
		this.idPersona = idPersona;
	}

	public BigDecimal getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(BigDecimal idCarrera) {
		this.idCarrera = idCarrera;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarreraEstudianteId))
			return false;
		CarreraEstudianteId castOther = (CarreraEstudianteId) other;

		return ((this.getIdPersona() == castOther.getIdPersona()) || (this
				.getIdPersona() != null && castOther.getIdPersona() != null && this
				.getIdPersona().equals(castOther.getIdPersona())))
				&& ((this.getIdCarrera() == castOther.getIdCarrera()) || (this
						.getIdCarrera() != null
						&& castOther.getIdCarrera() != null && this
						.getIdCarrera().equals(castOther.getIdCarrera())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdPersona() == null ? 0 : this.getIdPersona().hashCode());
		result = 37 * result
				+ (getIdCarrera() == null ? 0 : this.getIdCarrera().hashCode());
		return result;
	}

}
