// default package
// Generated Oct 12, 2015 4:45:01 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia implements java.io.Serializable {

	private BigDecimal idMateria;
	private String nombreMateria;
	private BigDecimal creditos;
	private Character estadoMateria;
	private Set matriculas = new HashSet(0);
	private Set carreras = new HashSet(0);

	public Materia() {
	}

	public Materia(BigDecimal idMateria) {
		this.idMateria = idMateria;
	}

	public Materia(BigDecimal idMateria, String nombreMateria,
			BigDecimal creditos, Character estadoMateria, Set matriculas,
			Set carreras) {
		this.idMateria = idMateria;
		this.nombreMateria = nombreMateria;
		this.creditos = creditos;
		this.estadoMateria = estadoMateria;
		this.matriculas = matriculas;
		this.carreras = carreras;
	}

	public BigDecimal getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(BigDecimal idMateria) {
		this.idMateria = idMateria;
	}

	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}

	public BigDecimal getCreditos() {
		return this.creditos;
	}

	public void setCreditos(BigDecimal creditos) {
		this.creditos = creditos;
	}

	public Character getEstadoMateria() {
		return this.estadoMateria;
	}

	public void setEstadoMateria(Character estadoMateria) {
		this.estadoMateria = estadoMateria;
	}

	public Set getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set matriculas) {
		this.matriculas = matriculas;
	}

	public Set getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set carreras) {
		this.carreras = carreras;
	}

}
