package co.ueb.matriculas.model;

// Generated Oct 13, 2015 8:11:29 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * MateriaMatriculaId generated by hbm2java
 */
public class MateriaMatriculaId implements java.io.Serializable {

	private BigDecimal idMateria;
	private BigDecimal idMatricula;

	public MateriaMatriculaId() {
	}

	public MateriaMatriculaId(BigDecimal idMateria, BigDecimal idMatricula) {
		this.idMateria = idMateria;
		this.idMatricula = idMatricula;
	}

	public BigDecimal getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(BigDecimal idMateria) {
		this.idMateria = idMateria;
	}

	public BigDecimal getIdMatricula() {
		return this.idMatricula;
	}

	public void setIdMatricula(BigDecimal idMatricula) {
		this.idMatricula = idMatricula;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MateriaMatriculaId))
			return false;
		MateriaMatriculaId castOther = (MateriaMatriculaId) other;

		return ((this.getIdMateria() == castOther.getIdMateria()) || (this
				.getIdMateria() != null && castOther.getIdMateria() != null && this
				.getIdMateria().equals(castOther.getIdMateria())))
				&& ((this.getIdMatricula() == castOther.getIdMatricula()) || (this
						.getIdMatricula() != null
						&& castOther.getIdMatricula() != null && this
						.getIdMatricula().equals(castOther.getIdMatricula())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdMateria() == null ? 0 : this.getIdMateria().hashCode());
		result = 37
				* result
				+ (getIdMatricula() == null ? 0 : this.getIdMatricula()
						.hashCode());
		return result;
	}

}
