package co.ueb.matriculas.model;

// Generated Oct 15, 2015 8:58:55 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia implements java.io.Serializable {

	private BigDecimal idMateria;
	private String nombreMateria;
	private BigDecimal creditos;
	private Character estadoMateria;
	private Set materiaMatriculas = new HashSet(0);
	private Set carreraMaterias = new HashSet(0);

	public Materia() {
	}

	public Materia(BigDecimal idMateria) {
		this.idMateria = idMateria;
	}

	public Materia(BigDecimal idMateria, String nombreMateria,
			BigDecimal creditos, Character estadoMateria,
			Set materiaMatriculas, Set carreraMaterias) {
		this.idMateria = idMateria;
		this.nombreMateria = nombreMateria;
		this.creditos = creditos;
		this.estadoMateria = estadoMateria;
		this.materiaMatriculas = materiaMatriculas;
		this.carreraMaterias = carreraMaterias;
	}

	public BigDecimal getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(BigDecimal idMateria) {
		this.idMateria = idMateria;
	}

	public String getNombreMateria() {
		return this.nombreMateria;
	}

	public void setNombreMateria(String nombreMateria) {
		this.nombreMateria = nombreMateria;
	}

	public BigDecimal getCreditos() {
		return this.creditos;
	}

	public void setCreditos(BigDecimal creditos) {
		this.creditos = creditos;
	}

	public Character getEstadoMateria() {
		return this.estadoMateria;
	}

	public void setEstadoMateria(Character estadoMateria) {
		this.estadoMateria = estadoMateria;
	}

	public Set getMateriaMatriculas() {
		return this.materiaMatriculas;
	}

	public void setMateriaMatriculas(Set materiaMatriculas) {
		this.materiaMatriculas = materiaMatriculas;
	}

	public Set getCarreraMaterias() {
		return this.carreraMaterias;
	}

	public void setCarreraMaterias(Set carreraMaterias) {
		this.carreraMaterias = carreraMaterias;
	}

}
