// default package
// Generated 11-oct-2015 23:22:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula implements java.io.Serializable {

	private BigDecimal idMatricula;
	private Persona persona;
	private BigDecimal totalCreditos;
	private BigDecimal totalMatricula;
	private Character estadoMatricula;
	private Set materias = new HashSet(0);

	public Matricula() {
	}

	public Matricula(BigDecimal idMatricula) {
		this.idMatricula = idMatricula;
	}

	public Matricula(BigDecimal idMatricula, Persona persona,
			BigDecimal totalCreditos, BigDecimal totalMatricula,
			Character estadoMatricula, Set materias) {
		this.idMatricula = idMatricula;
		this.persona = persona;
		this.totalCreditos = totalCreditos;
		this.totalMatricula = totalMatricula;
		this.estadoMatricula = estadoMatricula;
		this.materias = materias;
	}

	public BigDecimal getIdMatricula() {
		return this.idMatricula;
	}

	public void setIdMatricula(BigDecimal idMatricula) {
		this.idMatricula = idMatricula;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public BigDecimal getTotalCreditos() {
		return this.totalCreditos;
	}

	public void setTotalCreditos(BigDecimal totalCreditos) {
		this.totalCreditos = totalCreditos;
	}

	public BigDecimal getTotalMatricula() {
		return this.totalMatricula;
	}

	public void setTotalMatricula(BigDecimal totalMatricula) {
		this.totalMatricula = totalMatricula;
	}

	public Character getEstadoMatricula() {
		return this.estadoMatricula;
	}

	public void setEstadoMatricula(Character estadoMatricula) {
		this.estadoMatricula = estadoMatricula;
	}

	public Set getMaterias() {
		return this.materias;
	}

	public void setMaterias(Set materias) {
		this.materias = materias;
	}

}
