package co.ueb.matriculas.model;

// Generated 02-nov-2015 12:47:33 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private BigDecimal idPersona;
	private Perfil perfil;
	private String nombrePersona;
	private String apellidosPersona;
	private Date fechaNacimiento;
	private String lugarNacimiento;
	private String direccion;
	private String correoElectronico;
	private Character estadoPersona;
	private BigDecimal promedio;
	private String usuario;
	private String contrasena;
	private Set matriculas = new HashSet(0);
	private Set carreraEstudiantes = new HashSet(0);
	private Set telefonoses = new HashSet(0);

	public Persona() {
	}

	public Persona(String usuario, String contrasena) {
		super();
		this.usuario = usuario;
		this.contrasena = contrasena;
	}

	public Persona(BigDecimal idPersona) {
		this.idPersona = idPersona;
	}

	public Persona(BigDecimal idPersona, Perfil perfil, String nombrePersona,
			String apellidosPersona, Date fechaNacimiento,
			String lugarNacimiento, String direccion, String correoElectronico,
			Character estadoPersona, BigDecimal promedio, String usuario,
			String contrasena, Set matriculas, Set carreraEstudiantes,
			Set telefonoses) {
		this.idPersona = idPersona;
		this.perfil = perfil;
		this.nombrePersona = nombrePersona;
		this.apellidosPersona = apellidosPersona;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarNacimiento = lugarNacimiento;
		this.direccion = direccion;
		this.correoElectronico = correoElectronico;
		this.estadoPersona = estadoPersona;
		this.promedio = promedio;
		this.usuario = usuario;
		this.contrasena = contrasena;
		this.matriculas = matriculas;
		this.carreraEstudiantes = carreraEstudiantes;
		this.telefonoses = telefonoses;
	}

	public BigDecimal getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(BigDecimal idPersona) {
		this.idPersona = idPersona;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getNombrePersona() {
		return this.nombrePersona;
	}

	public void setNombrePersona(String nombrePersona) {
		this.nombrePersona = nombrePersona;
	}

	public String getApellidosPersona() {
		return this.apellidosPersona;
	}

	public void setApellidosPersona(String apellidosPersona) {
		this.apellidosPersona = apellidosPersona;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getLugarNacimiento() {
		return this.lugarNacimiento;
	}

	public void setLugarNacimiento(String lugarNacimiento) {
		this.lugarNacimiento = lugarNacimiento;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	public Character getEstadoPersona() {
		return this.estadoPersona;
	}

	public void setEstadoPersona(Character estadoPersona) {
		this.estadoPersona = estadoPersona;
	}

	public BigDecimal getPromedio() {
		return this.promedio;
	}

	public void setPromedio(BigDecimal promedio) {
		this.promedio = promedio;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public Set getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set matriculas) {
		this.matriculas = matriculas;
	}

	public Set getCarreraEstudiantes() {
		return this.carreraEstudiantes;
	}

	public void setCarreraEstudiantes(Set carreraEstudiantes) {
		this.carreraEstudiantes = carreraEstudiantes;
	}

	public Set getTelefonoses() {
		return this.telefonoses;
	}

	public void setTelefonoses(Set telefonoses) {
		this.telefonoses = telefonoses;
	}

}
