// default package
// Generated 11-oct-2015 23:22:04 by Hibernate Tools 3.4.0.CR1

/**
 * Telefonos generated by hbm2java
 */
public class Telefonos implements java.io.Serializable {

	private TelefonosId id;
	private Persona persona;

	public Telefonos() {
	}

	public Telefonos(TelefonosId id, Persona persona) {
		this.id = id;
		this.persona = persona;
	}

	public TelefonosId getId() {
		return this.id;
	}

	public void setId(TelefonosId id) {
		this.id = id;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
