package co.ueb.matriculas.model;

// Generated Nov 1, 2015 5:44:57 PM by Hibernate Tools 4.3.1

/**
 * Telefonos generated by hbm2java
 */
public class Telefonos implements java.io.Serializable {

	private TelefonosId id;
	private Persona persona;

	public Telefonos() {
	}

	public Telefonos(TelefonosId id, Persona persona) {
		this.id = id;
		this.persona = persona;
	}

	public TelefonosId getId() {
		return this.id;
	}

	public void setId(TelefonosId id) {
		this.id = id;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
